// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgxpool"
)

// New creates a new Queries instance backed by a pgxpool.Pool.
func New(db *pgxpool.Pool) *Queries {
	return &Queries{db: db}
}

// Queries holds the database connection pool and implements Querier.
type Queries struct {
	db *pgxpool.Pool
}
